#!/bin/python3

x = int(input("Enter your score: "))

  
if x <= 50 :
  print("Grade: 1")
  
elif x <= 55  :
  print("Grade: 1.5")
  
elif x <= 60  :
  print("Grade: 2")
  
elif x <= 65  :
  print("Grade: 2.5")
  
elif x <= 70  :
  print("Grade: 3")
  
elif x <= 75 :
  print("Grade: 3.5")
  
elif x <= 80 :
  print("Grade: 4")
  
else:
  print("Grade: 0")


  

  
