#!/bin/python3

PRINT ("BMI CALCULATOR")
print ("\n")

f_name = inputs("Enter Name:")
height = float(input("Enter height in cm: ")
weight = float(input("Enter weight in kg: "))

BMI = weight / (height/100)**2

print ("\n")
print("You BMI is:", BMI)
print ("\n")

if BMI <= 18.4:
    print(fname, ", you are underweight!")
   
elif BMI <= 24.9:
    print(f_name, ", you are healthy!")
   
elif BMI <= 29.9:
    print(f_name, ", you are over weight!")
   
elif BMI <= 34.9:
    print(f_name, ", you are severely over weight!")
   
elif BMI <= 39.9:
    print(f_name, ", you are obese!")
   
else:
    print(f_name ", you are severely obese!")
