#!/bin/python3

"""
1. Create a list [10,20,30,40,50]
2. Access the first and last number.
3. Replace the third number. [35]
4. Add one more number. [60]
5. Remove one number by value. [10]
6. Loop through and print: "The remaining number is "
"""

number = [10,20,30,40,50]  #1

print ("First Number: ", number[0]) #2
print ("Final Number: ", number[-1]) #2

number [2] = 35  #3

number.append(60) #4

number.remove(10) #5

for numbers in number: 
    print("The remaining numbers is ",numbers) #6
